[package]
name = "hephaestus"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
tokio = { version = "1.35", features = ["full", "test-util"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tree-sitter = { version = "0.20" }
blake3 = "0.3"
tree-sitter-rust = "0.20"
tree-sitter-c = "0.20"
tempfile = "3.10"
sha2 = "0.10"
backtrace = "0.3"
libc = "0.2"
futures = "0.3.32"
flate2 = "1.1.9"
similar = "2.4"
clap = { version = "4.4", features = ["derive"] }
