use crate::error::Result;
use crate::memory::evo_genome::{SemanticClusterer, WingManager};
use crate::memory::genome_store::{GenomeStore, RepairGenome};
use std::sync::Arc;
use tokio::sync::Mutex;

/// The Wild Monkey actor generates random patches to explore the solution space.
/// Now enhanced with memory: it queries past successful repairs in the same wing or semantic cluster.
pub struct WildMonkey;

impl WildMonkey {
    /// Generate a set of patches based on the genome and telemetry, using historical successful repairs
    /// from the same wing or semantic cluster as a guide.
    ///
    /// # Arguments
    ///
    /// * `genome` - The genome to update with generated hypotheses
    /// * `telemetry` - Telemetry data that triggered the repair attempt
    /// * `genome_store` - Shared genome store to query for past successful repairs
    ///
    /// # Returns
    ///
    /// * `Ok(vec![patch1, patch2])` - The generated patches
    /// * `Err(HephaestusError)` if patch generation fails
    pub async fn generate_patches(
        &self,
        genome: &mut RepairGenome,
        telemetry: &str,
        genome_store: &Arc<Mutex<GenomeStore>>,
    ) -> Result<Vec<String>> {
        // First, compute the wing and semantic cluster for the current genome using temporary managers.
        // This is necessary because the genome may not have these fields set yet (before storage).
        let wing = {
            let mut wing_manager = WingManager::new();
            wing_manager.assign_wing(genome)
        };
        let semantic_cluster = {
            let mut clusterer = SemanticClusterer::new();
            clusterer.assign_cluster(genome)
        };

        // Query the genome store for past successful repairs that match either wing or cluster.
        let mut historical_patches = Vec::new();
        {
            let store = genome_store.lock().await;
            let successful_genomes = store.get_successful_genomes()?;
            for past_genome in successful_genomes {
                // Check if the past genome matches wing or cluster.
                let matches_wing = past_genome.wing.as_ref() == Some(&wing);
                let matches_cluster = past_genome.semantic_cluster == Some(semantic_cluster);
                if matches_wing || matches_cluster {
                    // If there is a final repaired code, we can derive a patch by comparing
                    // original_code and final_repaired_code. For simplicity, we just use the final
                    // repaired code as a patch hypothesis.
                    if let Some(ref repaired_code) = past_genome.final_repaired_code {
                        historical_patches.push(repaired_code.clone());
                    }
                }
            }
        }

        // Generate base patches as before (fallback if no historical patches found).
        let mut base_patches = Vec::new();
        let patch1 = format!(
            "// Generated by Wild Monkey based on telemetry: {}\n{}",
            telemetry, genome.original_code
        );
        base_patches.push(patch1);

        // Create a simple variant that adds a comment
        let patch2 = format!(
            "// Patch attempt 1: {}\n{}",
            telemetry,
            genome.original_code.replace("fn ", "fn /* patched */ ")
        );
        base_patches.push(patch2);

        // If we have historical patches, we can use them as the primary hypotheses.
        // We'll combine: first the historical patches (up to 2), then fill with base patches if needed.
        let mut patches = Vec::new();
        for p in historical_patches.into_iter().take(2) {
            patches.push(p);
        }
        while patches.len() < 2 {
            if let Some(p) = base_patches.pop() {
                patches.push(p);
            } else {
                break;
            }
        }

        // Update the genome's monkey_hypotheses with the generated patches.
        genome.monkey_hypotheses = patches.clone();

        Ok(patches)
    }
}
